//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirdTouch_Server.EntityFrameworkModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class active_users
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<decimal> location_latitude { get; set; }
        public Nullable<decimal> location_longitude { get; set; }
        public Nullable<int> active_mode { get; set; }
        public Nullable<System.DateTime> datetime_last_update { get; set; }
    }
}
