//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirdTouch_Server.EntityFrameworkModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class birdtouchEntities2 : DbContext
    {
        public birdtouchEntities2()
            : base("name=birdtouchEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<business_info> business_info { get; set; }
        public virtual DbSet<user_info> user_info { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
