//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirdTouch_Server.EntityFrameworkModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class saved_business
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int saved_contact_id { get; set; }
        public string description { get; set; }
    }
}
